version: '3.7'

networks:
  traefik:
    external: true

services:
  nginx:
    image: nginx:latest
    container_name: kopia-proxy-pass-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.kopia.rule: Host(`mon_kopia.com`)
      traefik.http.routers.kopia.entrypoints: https
      traefik.http.routers.kopia.tls: true
      traefik.http.routers.kopia.tls.certresolver: letsencrypt
      traefik.http.middlewares.kopia.ipwhitelist.sourcerange: "127.0.0.1/32, 1.2.3.4, 4.5.6.7"
      traefik.http.routers.kopia.middlewares: kopia@docker
      traefik.http.services.kopia.loadbalancer.server.port: 8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
