---
## connect
- name: "connect | connect repository"
  shell: "kopia repository connect s3 --bucket {{ kopia_bucket_name }} --access-key {{ kopia_access_key }} --secret-access-key {{ kopia_secret_access_key }} --endpoint {{ kopia_endpoint }} --password {{ kopia_endpoint_password }} --log-dir {{ kopia_log_dir }} --cache-directory {{ kopia_cache_directory }} --content-cache-size-mb {{ kopia_content_cache_size_mb }} --metadata-cache-size-mb {{ kopia_metadata_cache_size_mb }}"
  tags:
    - kopia
    - kopia_connect

- name: "connect | register repository status"
  shell: "kopia repository status"
  register: kopia_status
  tags:
    - kopia
    - kopia_connect

- name : "connect | check repository status"
  debug:
    var: kopia_status.stdout_lines
  tags:
    - kopia
    - kopia_connect

- name: "connect | set upload max"
  shell: "kopia repository throttle set --upload-bytes-per-second={{ kopia_upload_max }}"
  when: kopia_upload_max is defined
  register: kopia_upload_max_reg
  tags:
    - kopia
    - kopia_connect
- name : "connect | check upload max throttle"
  debug:
    var: kopia_upload_max_reg.stderr_lines
  when: kopia_upload_max is defined
  tags:
    - kopia
    - kopia_connect

- name: "connect | register upload max"
  shell: "kopia repository throttle get"
  when: kopia_upload_max is defined
  register: kopia_upload_max_get
  tags:
    - kopia
    - kopia_connect
- name : "connect | check upload max"
  debug:
    var: kopia_upload_max_get.stdout_lines
  when: kopia_upload_max is defined
  tags:
    - kopia
    - kopia_connect

- name: "kopia | copy kopiaignore list in path backuped"
  template:
    src: excludes.list.j2
    dest: "{{ item.path }}/.kopiaignore"
    owner: root
    group: root
    mode: 0644
  loop: "{{ kopia_exclude_list }}"
  when: kopia_exclude_list is defined
  tags:
    - kopia
    - kopia_exclude
