---
- name: "UI | add service for ui"
  template:
    src: systemd/kopia_ui.service.j2
    dest: "/etc/systemd/system/kopia_ui.service"
    owner: root
    group: root
    mode: 0600
  tags:
    - kopia
    - kopia_ui

- name: "UI | enable (without starting) kopia_ui service"
  systemd:
    name: kopia_ui
    enabled: yes
    daemon_reload: yes
  ignore_errors: '{{ ansible_check_mode }}'
  when: kopia_ui_service_enable == true
  tags:
    - kopia
    - kopia_ui

- name: "UI | enable and start kopia-ui service "
  systemd:
    name: kopia_ui
    enabled: yes
    state: started
    daemon_reload: yes
  ignore_errors: '{{ ansible_check_mode }}'
  when: kopia_ui_service_start == true
  tags:
    - kopia
    - kopia_ui
