---
## kopia  install
- name: 'kopia | install'
  import_tasks: "install.yml"
  tags:
    - kopia
    - kopia_install

## kopia create repo
- name: 'kopia | create repo'
  import_tasks:
    - install.yml
    - create_repo.yml
  tags:
    - kopia_create_repo

## kopia connect repo
- name: 'kopia | connect repo'
  import_tasks: "connect.yml"
  tags:
    - kopia
    - kopia_connect
