---
## kopia  install
- name: 'kopia | install'
  import_tasks: "install.yml"
  tags:
    - kopia
    - kopia_install
    - kopia_create

## kopia create repo
- name: 'kopia | create repo'
  import_tasks:  "create_repo.yml"
  tags:
    - kopia
    - kopia_create
  when:
    - kopia_create_repo_enable

## kopia connect repo
- name: 'kopia | connect repo'
  import_tasks: "connect.yml"
  tags:
    - kopia
    - kopia_connect

## kopia ui
- name: 'kopia ui | add service'
  import_tasks: "kopia_ui.yml"
  tags:
    - kopia
    - kopia_ui
  when: kopia_ui_install == true

## kopia crontab
- name: Include cron.yml
  include: cron.yml
  when: kopia_cron is defined
  tags:
    - kopia
    - kopia_cron
  when: kopia_cron is defined
