---
## retention
- name: "Retention | add global retention"
  shell: "kopia policy set --global --keep-latest {{ kopia_global_retention['keep_latest'] }} --keep-hourly {{ kopia_global_retention['keep_hourly'] }} --keep-daily {{ kopia_global_retention['keep_daily'] }} --keep-weekly {{ kopia_global_retention['keep_weekly'] }} --keep-monthly {{ kopia_global_retention['keep_monthly'] }} --keep-annual {{ kopia_global_retention['keep_annual'] }}"
  when: kopia_global_retention is defined
  tags:
    - kopia
    - kopia_global_retention

- name: "Retention | register global policy"
  shell: "kopia policy show --global --json | jq .retention"
  when: kopia_global_retention is defined
  register: kopia_global_retention_reg
  tags:
    - kopia
    - kopia_global_retention
- name : "Retention | show global policy"
  debug:
    var: kopia_global_retention_reg.stdout_lines
  when: kopia_global_retention is defined
  tags:
    - kopia
    - kopia_global_retention
