---
- name: "Script | add script for check latest backup status"
  template:
    src: script/check_kopia.sh.j2
    dest: "/usr/local/bin/check_kopia.sh"
    owner: root
    group: root
    mode: 0755
  when: kopia_script_enable == true
  tags:
    - kopia
    - kopia_script

- name: "Script | add crontab for script"
  cron:
    name: kopia check script and store result into /tmp/kopia_status
    minute: "{{ kopia_script_cron_minute }}"
    hour: "{{ kopia_script_cron_hour }}"
    day: "{{ kopia_script_cron_day }}"
    month: "{{ kopia_script_cron_month }}"
    weekday: "{{ kopia_script_cron_weekday }}"
    user: "{{ kopia_script_cron_user }}"
    job: "/usr/local/bin/check_kopia.sh >/dev/null 2>&1"
    cron_file: kopia
  when:
    - kopia_script_enable == true
  tags:
    - kopia
    - kopia_script

- name: "Script | add crontab for script at reboot"
  cron:
    name: kopia check script and store result into /tmp/kopia_status
    special_time: reboot
    user: root
    job: "/usr/local/bin/check_kopia.sh >/dev/null 2>&1"
    cron_file: kopia
  when:
    - kopia_script_enable == true
  tags:
    - kopia
    - kopia_script
