---
- name: "Script | add script for check latest backup status"
  template:
    src: script/check_kopia.sh.j2
    dest: "/usr/local/bin/check_kopia.sh"
    owner: root
    group: root
    mode: 0755
  tags:
    - kopia
    - kopia_script

- name: "Script | add sudo rigth for zabbix"
  template:
    src: sudo/zabbix_kopia
    dest: "/etc/sudoers.d/zabbix_kopia"
    owner: root
    group: root
    mode: 0440
  when: kopia_zabbix_enable is defined
  tags:
    - kopia
    - kopia_script

- name: "Script | add cron to purge zabbix cli log and content log kopia cache"
  cron:
    name: kopia_purge_log"
    minute: "0"
    hour: "9"
    user: root
    job: '/usr/bin/find /root/.cache/kopia/ -mtime +1 -type f -name "kopia*list*.log" -delete'
    cron_file: kopia_purge_log
  when: kopia_zabbix_enable is defined
  tags:
    - kopia
    - kopia_script
